name: nah
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  flutter_native_splash: ^2.4.5
  provider: ^6.1.2
  flutter_advanced_drawer: ^1.4.0
  go_router: ^15.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  audioplayers: ^6.4.0
  http: ^1.3.0
  sqflite: ^2.4.2
  path: ^1.9.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/hymnals/
    - assets/hymns/
    - assets/images/
    - assets/images/empty/
